//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberBought
    {
        public int Id { get; set; }
        public System.DateTime DateBought { get; set; }
        public byte LotNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public short NumberTypeId { get; set; }
        public short NumberWinLevelId { get; set; }
    
        public virtual NumberType NumberType { get; set; }
        public virtual NumberWinLevel NumberWinLevel { get; set; }
    }
}
